<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Listar.aspx.cs" Inherits="NTTDATAEXAMEN.vista.Listar" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Listar</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <script type="text/javascript"> 

        $(document).ready(function () {
            

            $('#ContentPlaceHolder1_btnBuscar').on("click", function () {
                $('#divLoading').show();
            });


            var valor = $("#ContentPlaceHolder1_hfDelete").val();

            if (valor >= 1) {
                $('#exampleModal').modal('show');
                $("#lblMensaje").html("El registro con ID: " + valor + " se elimino correctamente");
            }
            else if (valor == "-1") {
                $('#exampleModal').modal('show');
                $("#lblMensaje").html("Se ha producido un error.");
            }
            else
                $('#exampleModal').modal('hide');

                


        });

    </script>

        <asp:HiddenField ID="hfDelete" runat="server" Value="0" />

    <h1>Listar Control Cliente</h1>

    <div class="container">

        <div class="row">

            <div class="col-3">
                <div class="mb-1">
                    <asp:Label ID="lblCodigo" runat="server" CssClass="form-label" Text="Codigo: "></asp:Label>
                    <asp:TextBox ID="txtCodigo" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
            </div>


            <div class="col-3">
                <div class="mb-1">
                    <asp:Label ID="lblApellido" runat="server" CssClass="form-label" Text="Apellidos: "></asp:Label>
                    <asp:TextBox ID="txtApellido" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
            </div>

            <div class="col-3">
                <div class="mb-1">
                    <asp:Label ID="lblGenero" runat="server" CssClass="form-label" Text="Genero: "></asp:Label>
                    <asp:DropDownList ID="ddlGenero" runat="server" CssClass="form-select">
                    </asp:DropDownList>
                </div>
            </div>

            <div class="col-3">
                <div class="mb-1">
                    <asp:Label ID="lblNacionalidad" runat="server" CssClass="form-label" Text="Nacionalidad: "></asp:Label>
                    <asp:DropDownList ID="ddlNacionalidad" runat="server" CssClass="form-select">
                    </asp:DropDownList>
                </div>
            </div>

            <div class="col-3">
                <div class="mb-1">
                    <asp:Label ID="lblPerfil" runat="server" CssClass="form-label" Text="Perfil: "></asp:Label>
                    <asp:DropDownList ID="ddlPerfil" runat="server" CssClass="form-select">
                    </asp:DropDownList>
                </div>
            </div>

            
            <div class="col-3">
                <div class="mb-1 mt-4">
                    <asp:Label ID="Label1" runat="server" CssClass="form-label" Text=" "></asp:Label>
                    
                </div>
            </div>


        </div>

        <div class="row mt-4" style="max-height:600px;overflow-x:scroll;">
            <asp:GridView ID="gvCliente" runat="server" CssClass="table table-striped" AllowPaging="true" AutoGenerateColumns="false" OnPageIndexChanging="gvCliente_PageIndexChanging" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblId" Text="Id"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblId2" Text='<%# Eval("id") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblEmpresa" Text="Empresa"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblEmpresa2" Text='<%# Eval("empresa") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblNro_doi" Text="Nro_doi"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblNro_doi2" Text='<%# Eval("nro_doi") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblTipo_contrato" Text="Tipo_contrato"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblTipo_contrato2" Text='<%# Eval("tipo_contrato") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblTipo_software" Text="Tipo_software"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblTipo_software2" Text='<%# Eval("tipo_software") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblNro_empresas" Text="Nro_empresas"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblNro_empresas2" Text='<%# Eval("nro_empresas") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblNro_empresas_con_data" Text="Nro_empresas_con_data"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblNro_empresas_con_data2" Text='<%# Eval("nro_empresas_con_data") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblTipo_pago" Text="Tipo_pago"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblTipo_pago2" Text='<%# Eval("tipo_pago") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                 <Columns>
                     <asp:TemplateField>
                         <HeaderTemplate>
                             <asp:Label runat="server" ID="lblDeuda_anterior" Text="Deuda_anterior"></asp:Label>
                         </HeaderTemplate>
                         <ItemTemplate>
                             <asp:Label runat="server" ID="lblDeuda_anterior2" Text='<%# Eval("deuda_anterior") %>'></asp:Label>
                         </ItemTemplate>
                     </asp:TemplateField>
                 </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblDescuento" Text="Descuento"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblDescuento2" Text='<%# Eval("descuento") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblLicencia_anual" Text="Licencia_anual"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblLicencia_anual2" Text='<%# Eval("licencia_anual") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblTotal_a_pagar" Text="Total_a_pagar"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblTotal_a_pagar2" Text='<%# Eval("total_a_pagar") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblContacto_nombre" Text="Contacto_nombre"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblContacto_nombre2" Text='<%# Eval("contacto_nombre") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblContcto_telefono" Text="Contcto_telefono"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblContcto_telefono2" Text='<%# Eval("contcto_telefono") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblCompromiso_descripcion" Text="Compromiso_descripcion"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblCompromiso_descripcion2" Text='<%# Eval("compromiso_descripcion") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblCompromiso_fecha" Text="Compromiso_fecha"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblCompromiso_fecha2" Text='<%# Eval("compromiso_fecha") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblCompromiso_importe" Text="Compromiso_importe"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblCompromiso_importe2" Text='<%# Eval("compromiso_importe") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblObservacion" Text="Observacion"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblObservacion2" Text='<%# Eval("observacion") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblEstado" Text="Estado"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblEstado2" Text='<%# Eval("estado") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblFecha_vencimiento" Text="Fecha_vencimiento"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblFecha_vencimiento2" Text='<%# Eval("fecha_vencimiento") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblLimite_empresas" Text="Limite_empresas"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblLimite_empresas2" Text='<%# Eval("limite_empresas") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

                <Columns>
                    <asp:TemplateField>
                        <HeaderTemplate>
                            <asp:Label runat="server" ID="lblLimite_usuarios" Text="Limite_usuarios"></asp:Label>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label runat="server" ID="lblLimite_usuarios2" Text='<%# Eval("limite_usuarios") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>

            </asp:GridView>
        </div>


    </div>

    <!--
    <div id="divLoading" class="div-loading" style="display: none;">
        <asp:Image ID="imgLoading" runat="server" ImageUrl="~/img/loading.gif" />
    </div>
        -->
    <div class="modal fade" id="exampleModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Mensaje</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>
                        <label id="lblMensaje"></label>
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

</asp:Content>
